// Compiles Voting.sol with solc-js and writes the ABI + bytecode to
// artifacts/Voting.json. The ABI is also copied into the backend so the
// NestJS app can talk to the deployed contract.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import solc from 'solc';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'Voting.sol'), 'utf8');

const input = {
  language: 'Solidity',
  sources: { 'Voting.sol': { content: source } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object', 'metadata'] } },
  },
};

const output = JSON.parse(solc.compile(JSON.stringify(input)));
const errors = (output.errors ?? []).filter((e) => e.severity === 'error');
if (errors.length) {
  for (const e of errors) console.error(e.formattedMessage);
  process.exit(1);
}
for (const w of output.errors ?? []) console.warn(w.formattedMessage);

const contract = output.contracts['Voting.sol'].Voting;
const artifact = {
  contractName: 'Voting',
  compiler: `solc ${solc.version()}`,
  abi: contract.abi,
  bytecode: '0x' + contract.evm.bytecode.object,
  metadata: contract.metadata,
};

const artifactsDir = path.join(root, 'artifacts');
fs.mkdirSync(artifactsDir, { recursive: true });
fs.writeFileSync(path.join(artifactsDir, 'Voting.json'), JSON.stringify(artifact, null, 2));

const backendAbi = path.resolve(root, '..', 'backend', 'src', 'blockchain', 'voting.abi.ts');
fs.mkdirSync(path.dirname(backendAbi), { recursive: true });
fs.writeFileSync(
  backendAbi,
  '// AUTO-GENERATED by contracts/scripts/compile.mjs — do not edit by hand.\n' +
    'export const VOTING_ABI = ' +
    JSON.stringify(contract.abi, null, 2) +
    ' as const;\n',
);

console.log(`Compiled with ${artifact.compiler}`);
console.log(`  -> ${path.relative(root, path.join(artifactsDir, 'Voting.json'))}`);
console.log(`  -> ${path.relative(root, backendAbi)}`);
